
// DATA LocalStorage []
export const bookList_2 = [
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '1',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '2',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '3',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '4',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '5',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '6',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '7',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '8',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '9',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '10',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '11',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '12',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '13',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '14',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '15',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '16',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '17',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '18',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '19',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '20',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '21',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '22',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '23',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
    {
        book_image: 'https://storage.googleapis.com/du-prd/books/images/9780063226050.jpg',
        title: '24',
        list_name: 'Hardcover Fiction',
        description: 'item-card-desc">David Burroughs was once a devoted father to his three-year-old son Matthew, living a dream life just a short drive away from the working-class suburb where he and his wife, Cheryl, first fell in love--until one fateful night when David woke suddenly to discover Matthew had been murdered while',
        author: "Harlan Coben",
        // purchaseLinks: '',
    },
   
];